In [7]:
"""
Support: num of times the rule occurs in dataset
         computed by num of samples rule is valid
         can be normalized by diving num of samples 
"""

'\nSupport: num of times the rule occurs in dataset\n         computed by num of samples rule is valid\n         can be normalized by diving num of samples \n'

In [8]:
"""
How to Import Data:
"""
import numpy as np
dataset_filename = "affinity_dataset.txt"
X = np.loadtxt(dataset_filename)
num_samples, num_features = X.shape

# Shape of X
print("Shape:", X.shape)

# Last 5 samples of X
print(X[:5])

Shape: (100, 5)
[[0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 1.]
 [1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1.]]
